<a href="https://colab.research.google.com/github/siu1997/Big-Data-Analytics/blob/main/Practical%206/Practical_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practical no 6
#Classification
#Support Vector Machine 

Support Vector Machine or SVM is a supervised and linear Machine Learning algorithm most commonly used for solving classification problems and is also referred to as Support Vector Classification. 

SVM also supports the kernel method also called the kernel SVM which allows us to tackle non-linearity.



Importing the necessary libraries

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
Location="drive/My Drive/Dataset"

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv(Location+ "/apples_and_oranges.csv")

In [ ]:
df.head()

Weight  Size   Class
0      69  4.39  orange
1      69  4.21  orange
2      65  4.09  orange
3      72  5.85   apple
4      67  4.70  orange

Extracting Independent and dependent Variable

In [ ]:
x= df.iloc[:, [0, 1]].values  
y= df.iloc[:, 2].values  

In [ ]:
x, y

(array([[69.  ,  4.39],
        [69.  ,  4.21],
        [65.  ,  4.09],
        [72.  ,  5.85],
        [67.  ,  4.7 ],
        [73.  ,  5.68],
        [70.  ,  5.56],
        [75.  ,  5.11],
        [74.  ,  5.36],
        [65.  ,  4.27],
        [73.  ,  5.79],
        [70.  ,  5.47],
        [74.  ,  5.53],
        [68.  ,  4.47],
        [74.  ,  5.22],
        [65.  ,  4.48],
        [69.  ,  4.66],
        [75.  ,  5.25],
        [67.  ,  4.18],
        [74.  ,  5.5 ],
        [66.  ,  4.13],
        [70.  ,  4.83],
        [69.  ,  4.61],
        [68.  ,  4.08],
        [67.  ,  4.25],
        [71.  ,  5.35],
        [67.  ,  4.01],
        [70.  ,  4.22],
        [74.  ,  5.25],
        [71.  ,  5.26],
        [73.  ,  5.78],
        [66.  ,  4.68],
        [72.  ,  5.72],
        [73.  ,  5.17],
        [68.  ,  4.83],
        [69.  ,  4.11],
        [69.  ,  4.76],
        [74.  ,  5.48],
        [70.  ,  5.59],
        [73.  ,  5.03]]),
 array(['orange', 'orange', 'orange', 

splitting the dataset into train and test set

In [ ]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  

Feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)   

Fitting the SVM classifier to the training set:

In [ ]:
from sklearn.svm import SVC # "Support vector classifier"  
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(x_train, y_train) 

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

Predicting the test set result:

In [ ]:
y_pred= classifier.predict(x_test) 

In [ ]:
y_pred

array(['orange', 'orange', 'apple', 'orange', 'apple', 'orange', 'apple',
       'apple', 'orange', 'apple'], dtype=object)

In [ ]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred) 

In [ ]:
cm

array([[5, 0],
       [0, 5]])

#Decision Tree

Decision Tree is a Supervised learning technique that can be used for both classification and Regression problems, but mostly it is preferred for solving Classification problems. It is a tree-structured classifier, where internal nodes represent the features of a dataset, branches represent the decision rules and each leaf node represents the outcome.

It is a graphical representation for getting all the possible solutions to a problem/decision based on given conditions.
It is called a decision tree because, similar to a tree, it starts with the root node, which expands on further branches and constructs a tree-like structure.

Decision Tree Terminologies

Root Node: Root node is from where the decision tree starts. It represents the entire dataset, which further gets divided into two or more homogeneous sets.
Leaf Node: Leaf nodes are the final output node, and the tree cannot be segregated further after getting a leaf node.
Splitting: Splitting is the process of dividing the decision node/root node into sub-nodes according to the given conditions.
Branch/Sub Tree: A tree formed by splitting the tree.
Pruning: Pruning is the process of removing the unwanted branches from the tree.
Parent/Child node: The root node of the tree is called the parent node, and other nodes are called the child nodes.

In [ ]:
# importing libraries  
import numpy as nm  
import matplotlib.pyplot as plt  
import pandas as pd  

In [ ]:
df1=pd.read_csv(Location+ "/apples_and_oranges.csv")

In [ ]:
x= df.iloc[:, [0, 1]].values  
y= df.iloc[:, 2].values  

In [ ]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  

In [ ]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)   

In [ ]:
#Fitting Decision Tree classifier to the training set  
from sklearn.tree import DecisionTreeClassifier  
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)  
classifier.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

Predicting the test result

In [ ]:
y_pred= classifier.predict(x_test)  

In [ ]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  

In [ ]:
print(cm)

[[5 0]
 [0 5]]
